### ISSUE TITLE
Informacion incorrecta

### ISSUE THREAD

**Issue by DD150602** [Vazz2004/vazz2004#1]
Los links apuntan a lugares que no son correctos

![links](https://github.com/Vazz2004/vazz2004/assets/121521754/5a7b29d7-fb76-4473-aa05-66610b602449)

y las estadísticas no corresponden

![Links](https://github.com/Vazz2004/vazz2004/assets/121521754/dc069fca-02c8-4350-a4a2-138ef60bb6a8)

**Comment by Vazz2004** [comment]
Hola si estoy en desarrollo muy pronto estará completo muchas gracias por estar pendiente

**Comment by Vazz2004** [comment]
Muchas gracias por feedback, los links ya apuntan donde corresponden y toda la correcciones fueron tomadas en cuenta
